name       : python-ecdsa
version    : 0.16.1
release    : 7
source     :
    - https://github.com/tlsfuzzer/python-ecdsa/archive/python-ecdsa-0.16.1.tar.gz : 3b9fb3cc04d7375e1087dc5b31d6e3edd76a07b307f417b78b8924e164438828
license    : MIT
component  : programming.python
summary    : ECDSA cryptographic signature library
description: |
    ECDSA cryptographic signature library
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
