name       : python-ecdsa
version    : '0.15'
release    : 6
source     :
    - https://github.com/warner/python-ecdsa/archive/python-ecdsa-0.15.tar.gz : 1fc04999670beb29bb919acad291aa829c126cc5d322e96d43bcda1994d20570
license    : MIT
component  : programming.python
summary    : ECDSA cryptographic signature library
description: |
    ECDSA cryptographic signature library
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
